apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-pv-claim
  namespace: hajer-tawazun
  labels:
    app: sql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi