apiVersion: v1
kind: Service
metadata:
  name: tawazun-serv
spec:
 selector:
   app: tawazun-web
 type: NodePort
 ports:
    - protocol: TCP
      port: 8080  #This is a serive port
      targetPort: 8080 #This is the target port of the pods
      nodePort: 30020 #This port is enable on node to send the traffic
