apiVersion: v1
kind: Service
metadata:
  name: tawazun-svc
  namespace: hajer-tawazun
  labels: 
    name: hajer
spec:
  selector:
    app: tawazun
    service: tawazun-svc
 type: NodePort
  ports:
    - protocol: TCP
      port: 80 #This is a serive port
      targetPort: 8080 #This is the target port of the pods
      nodport: 32000 #This port is enable on node to send the traffic